### ISSUE TITLE
Zigbee devices stoped working

### ISSUE THREAD

**Issue by happychameleon** [WebThingsIO/zigbee-adapter#263]
After the latest update, my connected zigbee devices have stoped working. These are all ikea tradfri devices which had previously worked flawlessly with the gateway.

**Comment by mrstegeman** [comment]
All devices? Do you have any errors in your log?

**Comment by happychameleon** [comment]
Yes all devices, and also plenty of errors:
``2020-12-03 00:00:32.559 INFO   : calendar: setCachedValueAndNotify for property reason from Wednesday to Thursday for calendar
2020-12-03 00:05:33.839 INFO   : Opening database: /home/pi/.webthings/log/logs.sqlite3
2020-12-03 00:05:36.980 INFO   : HTTPS server listening on port 4443
2020-12-03 00:05:36.983 INFO   : Redirector listening on port 8080
2020-12-03 00:05:37.037 DEBUG  : Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2020-12-03 00:05:37.798 DEBUG  : Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2020-12-03 00:05:47.352 ERROR  : Error getting value for thingId: zb-bc33acfffe88efd0 property: on
2020-12-03 00:05:47.354 ERROR  : getProperty: device: zb-bc33acfffe88efd0 not found.
2020-12-03 00:05:47.357 WARN   : Rule get failed { code: 500,
  message: 'getProperty: device: zb-bc33acfffe88efd0 not found.' }
2020-12-03 00:05:47.359 ERROR  : Error getting value for thingId: zb-bc33acfffe88efd0 property: on
2020-12-03 00:05:47.361 ERROR  : getProperty: device: zb-bc33acfffe88efd0 not found.
2020-12-03 00:05:47.363 WARN   : Rule get failed { code: 500,
  message: 'getProperty: device: zb-bc33acfffe88efd0 not found.' }
2020-12-03 00:05:47.365 ERROR  : Error getting value for thingId: zb-bc33acfffe0c0d8c property: on
2020-12-03 00:05:47.366 ERROR  : getProperty: device: zb-bc33acfffe0c0d8c not found.
2020-12-03 00:05:47.368 WARN   : Rule get failed { code: 500,
  message: 'getProperty: device: zb-bc33acfffe0c0d8c not found.' }
2020-12-03 00:05:47.370 ERROR  : Error getting value for thingId: zb-bc33acfffe0c0d8c property: on
2020-12-03 00:05:47.371 ERROR  : getProperty: device: zb-bc33acfffe0c0d8c not found.
2020-12-03 00:05:47.373 WARN   : Rule get failed { code: 500,
  message: 'getProperty: device: zb-bc33acfffe0c0d8c not found.' }
2020-12-03 00:05:47.375 ERROR  : Error getting value for thingId: zb-bc33acfffe88efd0 property: on
2020-12-03 00:05:47.376 ERROR  : getProperty: device: zb-bc33acfffe88efd0 not found.
2020-12-03 00:05:47.378 WARN   : Rule get failed { code: 500,
  message: 'getProperty: device: zb-bc33acfffe88efd0 not found.' }``

````

**Comment by happychameleon** [comment]
Not sure how helpful that is

**Comment by mrstegeman** [comment]
Those are all expected log lines. Nothing else?

**Comment by happychameleon** [comment]
Okay found a more useful part of the log: 
 
```
Loading add-on calendar from /home/pi/.webthings/addons/calendar
2020-12-03 23:29:08.738 INFO   : philips-hue-adapter: Loading add-on philips-hue-adapter from /home/pi/.webthings/addons/philips-hue-adapter
2020-12-03 23:29:08.741 INFO   : thing-url-adapter: Starting mDNS discovery
2020-12-03 23:29:08.743 INFO   : pulse-adapter: Loading add-on pulse-adapter from /home/pi/.webthings/addons/pulse-adapter
2020-12-03 23:29:08.746 INFO   : zigbee-adapter: Loading add-on zigbee-adapter from /home/pi/.webthings/addons/zigbee-adapter
2020-12-03 23:29:08.748 INFO   : homekit-adapter: Loading add-on homekit-adapter from /home/pi/.webthings/addons/homekit-adapter
2020-12-03 23:29:09.359 ERROR  : zwave-adapter: Failed to start add-on zwave-adapter: Unable to find ZWave adapter
2020-12-03 23:29:10.159 INFO   : Loading add-on: zigbee-adapter
2020-12-03 23:29:10.162 INFO   : Finished updating add-ons
2020-12-03 23:29:10.921 INFO   : homekit-adapter: Found IP device: { name: 'Philips hue - 0CD711',
2020-12-03 23:29:10.922 INFO   : homekit-adapter:   address: '192.168.1.132',
2020-12-03 23:29:10.924 INFO   : homekit-adapter:   port: 8080,
2020-12-03 23:29:10.925 INFO   : homekit-adapter:   'c#': 37,
2020-12-03 23:29:10.926 INFO   : homekit-adapter:   ff: 1,
2020-12-03 23:29:10.928 INFO   : homekit-adapter:   id: '24:E9:C6:CF:C6:54',
2020-12-03 23:29:10.929 INFO   : homekit-adapter:   md: 'BSB002',
2020-12-03 23:29:10.930 INFO   : homekit-adapter:   pv: '1.1',
2020-12-03 23:29:10.932 INFO   : homekit-adapter:   's#': 2,
2020-12-03 23:29:10.933 INFO   : homekit-adapter:   sf: 1,
2020-12-03 23:29:10.934 INFO   : homekit-adapter:   ci: 2 }
2020-12-03 23:29:10.935 INFO   : homekit-adapter: Error loading device 24:E9:C6:CF:C6:54: Error: no pairing data available
2020-12-03 23:29:10.937 INFO   : homekit-adapter:     at HomeKitDevice.promise.adapter.db.loadPairingData.then (/home/pi/.webthings/addons/homekit-adapter/lib/homekit-device.js:106:15)
2020-12-03 23:29:10.938 INFO   : homekit-adapter:     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-12-03 23:29:14.595 INFO   : zigbee-adapter: DEBUG config = ''
2020-12-03 23:29:15.038 INFO   : zigbee-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3
2020-12-03 23:29:15.129 INFO   : zigbee-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2020-12-03 23:29:15.481 INFO   : zigbee-adapter: this.driver = DeconzDriver {}
2020-12-03 23:29:15.484 INFO   : zigbee-adapter: DeconzDriver: Using serial port /dev/ttyACM0
2020-12-03 23:29:15.513 INFO   : zigbee-adapter: DeConz Firmware version: 26490700
2020-12-03 23:29:15.593 INFO   : zigbee-adapter: Kicking WatchDog for 3600 seconds
2020-12-03 23:29:15.619 INFO   : zigbee-adapter:          MAC Address: 00212effff04229b
2020-12-03 23:29:15.620 INFO   : zigbee-adapter:      Network PANID16: 7bc7
2020-12-03 23:29:15.621 INFO   : zigbee-adapter:       Network Addr16: 0000
2020-12-03 23:29:15.623 INFO   : zigbee-adapter:      Network PANID64: 00212effff04229b
2020-12-03 23:29:15.624 INFO   : zigbee-adapter: APS Designated Coordinator: 1
2020-12-03 23:29:15.625 INFO   : zigbee-adapter:        Scan Channels: 00100000
2020-12-03 23:29:15.626 INFO   : zigbee-adapter:          APS PANID64: 0000000000000000
2020-12-03 23:29:15.628 INFO   : zigbee-adapter:  Trust Center Addr64: 00212effff04229b
2020-12-03 23:29:15.629 INFO   : zigbee-adapter:        Security Mode: 3
2020-12-03 23:29:15.630 INFO   : zigbee-adapter:          Network Key: 28b68ba3d0e7937d78399bac2cbcdf00
2020-12-03 23:29:15.632 INFO   : zigbee-adapter:    Operating Channel: 20
2020-12-03 23:29:15.633 INFO   : zigbee-adapter:     Protocol Version: 267
2020-12-03 23:29:15.634 INFO   : zigbee-adapter:    Network Update ID: 0
2020-12-03 23:29:15.635 INFO   : zigbee-adapter:          Permit Join: 0
2020-12-03 23:29:15.637 INFO   : zigbee-adapter:         WatchDog TTL: 3600
2020-12-03 23:29:15.638 INFO   : zigbee-adapter:              Version: 26490700
2020-12-03 23:29:15.640 INFO   : zigbee-adapter: ZigbeeNode created: addr64: 00212effff04229b addr16: 0000
2020-12-03 23:29:15.641 INFO   : zigbee-adapter: ZigbeeNode created: addr64: 000b57fffe32d003 addr16: e773
2020-12-03 23:29:15.652 INFO   : zigbee-adapter: ZigbeeNode created: addr64: 000b57fffe30e290 addr16: 2894
2020-12-03 23:29:15.653 INFO   : zigbee-adapter: ZigbeeNode created: addr64: 000b57fffe2284df addr16: 90a3
2020-12-03 23:29:15.655 INFO   : zigbee-adapter: ZigbeeNode created: addr64: bc33acfffe88efd0 addr16: aacb
2020-12-03 23:29:15.656 INFO   : zigbee-adapter: ZigbeeNode created: addr64: bc33acfffe0c0d8c addr16: 894f
2020-12-03 23:29:15.657 INFO   : zigbee-adapter: ZigbeeNode created: addr64: 842e14fffe4156b6 addr16: 454b
2020-12-03 23:29:15.659 INFO   : zigbee-adapter: ZigbeeNode created: addr64: 842e14fffe44b887 addr16: a8ff
2020-12-03 23:29:15.692 INFO   : zigbee-adapter: ----- Scan Starting -----
2020-12-03 23:29:15.741 INFO   : zigbee-adapter: ----- Nodes -----
2020-12-03 23:29:15.742 INFO   : zigbee-adapter: Node: 00212effff04229b 0000 Name: zb-00212effff04229b-Dongle       rebindRequired: true endpoints: []
2020-12-03 23:29:15.743 INFO   : zigbee-adapter:   Neighbor: 000b57fffe2284df 90a3 DT: Router R: Sibling  PJ: N D:   1 LQI: 255
2020-12-03 23:29:15.744 INFO   : zigbee-adapter:   Neighbor: 000b57fffe32d003 e773 DT: Router R: Sibling  PJ: N D:   1 LQI: 255
2020-12-03 23:29:15.745 INFO   : zigbee-adapter:   Neighbor: 000b57fffe30e290 2894 DT: Router R: Sibling  PJ: N D:   1 LQI: 223
2020-12-03 23:29:15.746 INFO   : zigbee-adapter:   Neighbor: 842e14fffe4156b6 454b DT: Router R: Sibling  PJ: N D:   1 LQI: 255
2020-12-03 23:29:15.747 INFO   : zigbee-adapter: Node: 000b57fffe32d003 e773 Name: zb-000b57fffe32d003-dimmableLigh rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:15.749 INFO   : zigbee-adapter: Node: 000b57fffe30e290 2894 Name: zb-000b57fffe30e290-dimmableLigh rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:15.750 INFO   : zigbee-adapter: Node: 000b57fffe2284df 90a3 Name: zb-000b57fffe2284df-undefined    rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:15.751 INFO   : zigbee-adapter: Node: bc33acfffe88efd0 aacb Name: zb-bc33acfffe88efd0-button       rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:15.752 INFO   : zigbee-adapter: Node: bc33acfffe0c0d8c 894f Name: zb-bc33acfffe0c0d8c-button       rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:15.753 INFO   : zigbee-adapter: Node: 842e14fffe4156b6 454b Name: zb-842e14fffe4156b6-undefined    rebindRequired: true endpoints: [ '1', '242' ]
2020-12-03 23:29:15.756 INFO   : zigbee-adapter: Node: 842e14fffe44b887 a8ff Name: zb-842e14fffe44b887-undefined    rebindRequired: true endpoints: [ '1', '242' ]
2020-12-03 23:29:15.757 INFO   : zigbee-adapter: -----------------
2020-12-03 23:29:15.759 INFO   : zigbee-adapter: ----- Scan Complete -----
2020-12-03 23:29:16.131 INFO   : zigbee-adapter: zb-000b57fffe32d003-dimmableLight property: level profileId: 0104 endpoint: 1 clusterId: 0008 readRsp value: 100.0% (254)
2020-12-03 23:29:16.199 INFO   : zigbee-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2020-12-03 23:29:16.388 INFO   : zigbee-adapter: zb-000b57fffe32d003-dimmableLight property: on profileId: 0104 endpoint: 1 clusterId: 0006 readRsp value: on (1)
2020-12-03 23:29:16.720 INFO   : zigbee-adapter: zb-000b57fffe30e290-dimmableLight property: level profileId: 0104 endpoint: 1 clusterId: 0008 readRsp value: 100.0% (254)
2020-12-03 23:29:16.979 INFO   : zigbee-adapter: zb-000b57fffe30e290-dimmableLight property: on profileId: 0104 endpoint: 1 clusterId: 0006 readRsp value: on (1)
2020-12-03 23:29:17.313 INFO   : zigbee-adapter: zb-000b57fffe2284df-undefined property: level profileId: 0104 endpoint: 1 clusterId: 0008 readRsp value: 100.0% (254)
2020-12-03 23:29:17.581 INFO   : zigbee-adapter: zb-000b57fffe2284df-undefined property: on profileId: 0104 endpoint: 1 clusterId: 0006 readRsp value: on (1)
2020-12-03 23:29:17.692 INFO   : zigbee-adapter: Loading add-on zigbee-adapter from /home/pi/.webthings/addons/zigbee-adapter
2020-12-03 23:29:17.747 INFO   : zigbee-adapter: DEBUG config = ''
2020-12-03 23:29:17.938 INFO   : zigbee-adapter: zb-842e14fffe4156b6-undefined property: level profileId: 0104 endpoint: 1 clusterId: 0008 readRsp value: 100.0% (254)
2020-12-03 23:29:18.219 INFO   : zigbee-adapter: zb-842e14fffe4156b6-undefined property: on profileId: 0104 endpoint: 1 clusterId: 0006 readRsp value: on (1)
2020-12-03 23:29:18.642 ERROR  : roku-adapter: Discovery failed: Error: Could not find any Roku devices after 10 seconds
2020-12-03 23:29:19.224 INFO   : zigbee-adapter: ----- Nodes -----
2020-12-03 23:29:19.225 INFO   : zigbee-adapter: Node: 00212effff04229b 0000 Name: zb-00212effff04229b-Dongle       rebindRequired: true endpoints: []
2020-12-03 23:29:19.226 INFO   : zigbee-adapter:   Neighbor: 000b57fffe2284df 90a3 DT: Router R: Sibling  PJ: N D:   1 LQI: 255
2020-12-03 23:29:19.227 INFO   : zigbee-adapter:   Neighbor: 000b57fffe32d003 e773 DT: Router R: Sibling  PJ: N D:   1 LQI: 255
2020-12-03 23:29:19.228 INFO   : zigbee-adapter:   Neighbor: 000b57fffe30e290 2894 DT: Router R: Sibling  PJ: N D:   1 LQI: 223
2020-12-03 23:29:19.229 INFO   : zigbee-adapter:   Neighbor: 842e14fffe4156b6 454b DT: Router R: Sibling  PJ: N D:   1 LQI: 255
2020-12-03 23:29:19.230 INFO   : zigbee-adapter: Node: 000b57fffe32d003 e773 Name: zb-000b57fffe32d003-dimmableLigh rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:19.231 INFO   : zigbee-adapter: Node: 000b57fffe30e290 2894 Name: zb-000b57fffe30e290-dimmableLigh rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:19.232 INFO   : zigbee-adapter: Node: 000b57fffe2284df 90a3 Name: zb-000b57fffe2284df-undefined    rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:19.232 INFO   : zigbee-adapter: Node: bc33acfffe88efd0 aacb Name: zb-bc33acfffe88efd0-button       rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:19.233 INFO   : zigbee-adapter: Node: bc33acfffe0c0d8c 894f Name: zb-bc33acfffe0c0d8c-button       rebindRequired: true endpoints: [ '1' ]
2020-12-03 23:29:19.234 INFO   : zigbee-adapter: Node: 842e14fffe4156b6 454b Name: zb-842e14fffe4156b6-undefined    rebindRequired: true endpoints: [ '1', '242' ]
2020-12-03 23:29:19.235 INFO   : zigbee-adapter: Node: 842e14fffe44b887 a8ff Name: zb-842e14fffe44b887-undefined    rebindRequired: true endpoints: [ '1', '242' ]
2020-12-03 23:29:19.235 INFO   : zigbee-adapter: -----------------
2020-12-03 23:29:19.236 INFO   : zigbee-adapter: ----- Update Network Addresses Complete -----
2020-12-03 23:29:21.985 ERROR  : zigbee-adapter: [Error: Error Resource temporarily unavailable Cannot lock port]
2020-12-03 23:29:21.986 INFO   : zigbee-adapter: Serial ports that were found:
2020-12-03 23:29:22.234 INFO   : zigbee-adapter: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE1963106 found @ /dev/ttyACM0
2020-12-03 23:29:22.235 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyAMA0
2020-12-03 23:29:22.236 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS0
2020-12-03 23:29:22.237 ERROR  : zigbee-adapter: Failed to start add-on zigbee-adapter: No Zigbee dongle found
```

**Comment by mrstegeman** [comment]
```
2020-12-03 23:29:21.985 ERROR  : zigbee-adapter: [Error: Error Resource temporarily unavailable Cannot lock port]
2020-12-03 23:29:21.986 INFO   : zigbee-adapter: Serial ports that were found:
2020-12-03 23:29:22.234 INFO   : zigbee-adapter: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE1963106 found @ /dev/ttyACM0
2020-12-03 23:29:22.235 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyAMA0
2020-12-03 23:29:22.236 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS0
2020-12-03 23:29:22.237 ERROR  : zigbee-adapter: Failed to start add-on zigbee-adapter: No Zigbee dongle found
```

This is the bad part. Do you have something else on the system that's also using your Zigbee dongle? If not, does the problem persist after a reboot?

**Comment by happychameleon** [comment]
I've rebooted the system several times and it's not changed anything, the only thing that should be running on rpi that uses the dongle should be the gateway. I could check if it's running two gateways after the rebranding and update.

**Comment by mrstegeman** [comment]
Yeah, something like that is going on.

**Comment by happychameleon** [comment]
Okay very strange, just restarted again and saw the zigbee plugin is now on version 15.1 and everything is working again.

**Comment by mrstegeman** [comment]
I'll call that fixed :)

**Comment by Poisonsting** [comment]
I'm encountering this error again, consistently on version 21.1

`
2021-12-02 00:41:09.142 INFO   : zigbee-adapter: Probing serial ports
2021-12-02 00:41:09.152 INFO   : zigbee-adapter: ConBee Firmware version: 264a0700
2021-12-02 00:41:09.169 INFO   : zigbee-adapter: Node: undefined 75f7 not found
2021-12-02 00:41:09.173 INFO   : zigbee-adapter: Node: undefined 75f7 not found
2021-12-02 00:41:09.218 INFO   : zigbee-adapter: handleNetworkAddressResponse: Skipping: ec1bbdfffe76d00b due to unknown addr64
2021-12-02 00:41:09.245 INFO   : zigbee-adapter: handleNetworkAddressResponse: Skipping: ec1bbdfffe76d00b due to unknown addr64
2021-12-02 00:41:09.274 INFO   : zigbee-adapter: Kicking WatchDog for 3600 seconds
2021-12-02 00:41:09.290 INFO   : zigbee-adapter:          MAC Address: 00212effff053943
2021-12-02 00:41:09.291 INFO   : zigbee-adapter:      Network PANID16: 4f95
2021-12-02 00:41:09.291 INFO   : zigbee-adapter:       Network Addr16: 0000
2021-12-02 00:41:09.291 INFO   : zigbee-adapter:      Network PANID64: 00212effff053943
2021-12-02 00:41:09.291 INFO   : zigbee-adapter: APS Designated Coordinator: 1
2021-12-02 00:41:09.292 INFO   : zigbee-adapter:        Scan Channels: 00008000
2021-12-02 00:41:09.292 INFO   : zigbee-adapter:          APS PANID64: 0000000000000000
2021-12-02 00:41:09.292 INFO   : zigbee-adapter:  Trust Center Addr64: 00212effff053943
2021-12-02 00:41:09.292 INFO   : zigbee-adapter:        Security Mode: 3
2021-12-02 00:41:09.293 INFO   : zigbee-adapter:          Network Key: a442767118073a09ccf0debabb2fff00
2021-12-02 00:41:09.293 INFO   : zigbee-adapter:    Operating Channel: 15
2021-12-02 00:41:09.293 INFO   : zigbee-adapter:     Protocol Version: 267
2021-12-02 00:41:09.293 INFO   : zigbee-adapter:    Network Update ID: 0
2021-12-02 00:41:09.294 INFO   : zigbee-adapter:          Permit Join: 0
2021-12-02 00:41:09.294 INFO   : zigbee-adapter:         WatchDog TTL: 3600
2021-12-02 00:41:09.294 INFO   : zigbee-adapter:              Version: 264a0700
2021-12-02 00:41:09.295 INFO   : zigbee-adapter: ZigbeeNode created: addr64: 00212effff053943 addr16: 0000
2021-12-02 00:41:09.296 INFO   : zigbee-adapter: ZigbeeNode created: addr64: 90fd9ffffe645c0c addr16: 8b4f
2021-12-02 00:41:09.297 INFO   : zigbee-adapter: ZigbeeNode created: addr64: ec1bbdfffe76d00b addr16: 75f7
2021-12-02 00:41:09.297 INFO   : zigbee-adapter: ZigbeeNode created: addr64: f0d1b80000035cf7 addr16: 4f4f
2021-12-02 00:41:09.298 INFO   : zigbee-adapter: ZigbeeNode created: addr64: f0d1b80000031a62 addr16: 85c4
2021-12-02 00:41:09.298 INFO   : zigbee-adapter: ZigbeeNode created: addr64: f0d1b80000035b2f addr16: 0217
2021-12-02 00:41:09.298 INFO   : zigbee-adapter: ZigbeeNode created: addr64: f0d1b80000031ebf addr16: 9f8d
2021-12-02 00:41:09.308 INFO   : zigbee-adapter: ----- Scan Starting -----
2021-12-02 00:41:09.314 INFO   : zigbee-adapter: setPropertyValue property: locked for: zb-90fd9ffffe645c0c-DoorLock value: locked
2021-12-02 00:41:09.322 INFO   : zigbee-adapter: genOnOffEndpoints = [ 1 ]
2021-12-02 00:41:09.322 INFO   : zigbee-adapter: Processing endpoing 0 = 1
2021-12-02 00:41:09.328 INFO   : zigbee-adapter: ----- Nodes -----
2021-12-02 00:41:09.328 INFO   : zigbee-adapter: Node: 00212effff053943 0000 Name: zb-00212effff053943-Dongle       rebindRequired: true endpoints: []
2021-12-02 00:41:09.328 INFO   : zigbee-adapter:   Neighbor: ec1bbdfffe76d00b 75f7 DT: Router R: Sibling  PJ: N D:   1 LQI: 251
2021-12-02 00:41:09.329 INFO   : zigbee-adapter: Node: 90fd9ffffe645c0c 8b4f Name: zb-90fd9ffffe645c0c-DoorLock     rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.329 INFO   : zigbee-adapter: Node: ec1bbdfffe76d00b 75f7 Name: zb-ec1bbdfffe76d00b-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.329 INFO   : zigbee-adapter: Node: f0d1b80000035cf7 4f4f Name: zb-f0d1b80000035cf7-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.329 INFO   : zigbee-adapter: Node: f0d1b80000031a62 85c4 Name: zb-f0d1b80000031a62-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.330 INFO   : zigbee-adapter: Node: f0d1b80000035b2f 0217 Name: zb-f0d1b80000035b2f-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.330 INFO   : zigbee-adapter: Node: f0d1b80000031ebf 9f8d Name: zb-f0d1b80000031ebf-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.330 INFO   : zigbee-adapter: -----------------
2021-12-02 00:41:09.330 INFO   : zigbee-adapter: ----- Scan Complete -----
2021-12-02 00:41:09.491 INFO   : zigbee-adapter: zb-ec1bbdfffe76d00b-undefined property: on profileId: 0104 endpoint: 1 clusterId: 0006 readRsp value: off (0)
2021-12-02 00:41:09.494 INFO   : zigbee-adapter: ----- Nodes -----
2021-12-02 00:41:09.494 INFO   : zigbee-adapter: Node: 00212effff053943 0000 Name: zb-00212effff053943-Dongle       rebindRequired: true endpoints: []
2021-12-02 00:41:09.494 INFO   : zigbee-adapter:   Neighbor: ec1bbdfffe76d00b 75f7 DT: Router R: Sibling  PJ: N D:   1 LQI: 251
2021-12-02 00:41:09.494 INFO   : zigbee-adapter: Node: 90fd9ffffe645c0c 8b4f Name: zb-90fd9ffffe645c0c-DoorLock     rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.495 INFO   : zigbee-adapter: Node: ec1bbdfffe76d00b 75f7 Name: zb-ec1bbdfffe76d00b-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.495 INFO   : zigbee-adapter: Node: f0d1b80000035cf7 4f4f Name: zb-f0d1b80000035cf7-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.495 INFO   : zigbee-adapter: Node: f0d1b80000031a62 85c4 Name: zb-f0d1b80000031a62-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.495 INFO   : zigbee-adapter: Node: f0d1b80000035b2f 0217 Name: zb-f0d1b80000035b2f-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.496 INFO   : zigbee-adapter: Node: f0d1b80000031ebf 9f8d Name: zb-f0d1b80000031ebf-undefined    rebindRequired: true endpoints: [ '1' ]
2021-12-02 00:41:09.496 INFO   : zigbee-adapter: -----------------
2021-12-02 00:41:09.496 INFO   : zigbee-adapter: ----- Update Network Addresses Complete -----
2021-12-02 00:41:13.225 ERROR  : zigbee-adapter: [Error: Error Resource temporarily unavailable Cannot lock port]
2021-12-02 00:41:15.763 INFO   : Checking for add-on updates...
2021-12-02 00:41:16.064 INFO   : Finished updating add-ons
2021-12-02 00:41:17.240 ERROR  : zigbee-adapter: [Error: Error Resource temporarily unavailable Cannot lock port]
2021-12-02 00:41:17.241 INFO   : zigbee-adapter: Serial ports that were found:
2021-12-02 00:41:17.287 INFO   : zigbee-adapter: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE2147304 found @ /dev/ttyACM0
2021-12-02 00:41:17.288 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS0
2021-12-02 00:41:17.288 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS1
2021-12-02 00:41:17.289 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS2
2021-12-02 00:41:17.289 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS3
2021-12-02 00:41:17.290 ERROR  : zigbee-adapter: Failed to start add-on zigbee-adapter: No Zigbee dongle found
`
