### ISSUE TITLE
Release workflow failing

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/zigbee-adapter#344]
The following builds:
- linux-arm node:10
- linux-arm64, node:10
- linux-x64, node: 12

Fail with the same error:

```
Status: Downloaded newer image for webthingsio/toolchain-linux-arm-node-10:latest
WARNING: The requested image's platform (linux/arm/v6) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:path'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/lib/cli.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v10.24.1 --silent` to unset it.
Error: Process completed with exit code 11.
```

The linux-x64, node:14 build fails with:
```
ERROR: npm v10.8.1 is known not to run on Node.js v14.21.3.  This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at [https://nodejs.org/.](https://nodejs.org/)

ERROR:
/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/lib/utils/error-message.js:11
  er.message &&= replaceInfo(er.message)
             ^^^

SyntaxError: Unexpected token '&&='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/lib/cli/exit-handler.js:2:48)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v14.21.3 --silent` to unset it.
Error: Process completed with exit code 11.
```

The other builds were automatically cancelled.

See https://github.com/WebThingsIO/zigbee-adapter/actions/runs/9317603077

**Comment by tim-hellhake** [comment]
The node versions of the addon-builder images are currently broken.
This [line](https://github.com/WebThingsIO/addon-builder/blob/master/toolchain/linux-x64/node/Dockerfile#L35) updates npm to the latest version, which requires at least node 18.
After updating nvm to the latest version, this no longer happens.

**Comment by benfrancis** [comment]
I think I've fixed the addon-builder images for Node.js.

I tried to push a new release 0.23.0 but now there is a new error on the GitHub Action:

 Error: Missing download info for actions/upload-artifact@v1

**Comment by benfrancis** [comment]
I've fixed the upload-artifact error by upgrading the GitHub action https://github.com/WebThingsIO/zigbee-adapter/commit/425ca24d675468b28fe7f6e7810799c7cefab1af

I noticed the Node.js 10, 12 and 14 builds were disabled and on re-enabling them discovered they are currently broken (https://github.com/WebThingsIO/zigbee-adapter/issues/348) so they will need fixing before we can do another release.

**Comment by benfrancis** [comment]
I think the release workflow is close to working now, but it's failing to upload the build tarball:

```
Run actions/upload-release-asset@v1.0.1
  with:
    asset_path: zigbee-adapter-0.23.0-linux-x64-v20.tgz
    asset_name: zigbee-adapter-0.23.0-linux-x64-v20.tgz
    asset_content_type: application/gnutar
  env:
    UPLOAD_URL: 
    RELEASE_VERSION: 0.23.0
    GITHUB_TOKEN: ***
Error: Input required and not supplied: upload_url
```

**Comment by benfrancis** [comment]
I think "downloading the upload URL" is no longer working after upgrading the download-artifact and upload-artificat actions. Doesn't help that a lot of these actions are no longer supported.

Could try a different approach, e.g. https://github.com/marketplace/actions/get-the-upload-url-for-a-release

**Comment by benfrancis** [comment]
Fixed by 
- 425ca24d675468b28fe7f6e7810799c7cefab1af
- c2c1743819017415333365a08b331d9ae78b60f2
- 444ab003122838277bc0d4abd5cdf0ed55ecdec0
